language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25

    # Extras
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-25
    - extra-google-google_play_services
before_install:
  - openssl aes-256-cbc -K $encrypted_95e6a2aa17ed_key -iv $encrypted_95e6a2aa17ed_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google-services.json app
  - chmod +x gradlew
script: ./gradlew clean assembleDebug check lint
