language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
    - build-tools-25.0.1
    - android-25
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
before_script:
  - chmod +x gradlew setup.sh build.sh upload.sh
  - ./setup.sh
script: ./build.sh
after_success: ./upload.sh
after_failure:
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
  - cat app/build/reports/checkstyle.html
  - cat app/build/reports/findbugs.html
  - cat app/build/reports/pmd.html
