language: android
jdk: oraclejdk8
group: edge
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25

    # Extras
    - extra-android-m2repository
    - extra-google-m2repository
before_script:
  - mv travis-dummies/google-services.json app/google-services.json
  - mv travis-dummies/keystore.properties keystore.properties
  - mv travis-dummies/keystore.jks app/keystore.jks
  - chmod +x gradlew
script: ./gradlew clean assembleDebug check lint
