language: android
jdk: oraclejdk8
# See https://github.com/travis-ci/travis-ci/issues/5582
sudo: required
env:
  - BUILD_TOOLS_VERSION=26.0.2
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 300 # 5 minutes
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
install: nvm install 7
before_script:
  - chmod +x gradlew building/setup.sh building/build.sh building/upload.sh
  - building/setup.sh
script: ./gradlew clean assembleDebug check
# TODO add back once all NDA protected libraries have graduated to public alpha/beta
#script: building/build.sh
#after_success: building/upload.sh
after_failure:
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
  - cat app/build/reports/checkstyle/checkstyle.html
  - cat app/build/reports/findbugs.html
  - cat app/build/reports/pmd.html
